create table comments (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	comment TEXT NOT NULL,
	date INTEGER NOT NULL,
	post_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL
);
insert into comments (comment, date, post_id, user_id) values ('turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis', '1539840410', 3, 13);
insert into comments (comment, date, post_id, user_id) values ('id luctus nec molestie sed justo pellentesque viverra pede ac diam', '1540410030', 19, 20);
insert into comments (comment, date, post_id, user_id) values ('tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum', '1553025143', 2, 4);
insert into comments (comment, date, post_id, user_id) values ('vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa', '1557861065', 18, 2);
insert into comments (comment, date, post_id, user_id) values ('id luctus nec molestie sed justo pellentesque viverra pede ac', '1535202243', 16, 19);
insert into comments (comment, date, post_id, user_id) values ('sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi', '1545428767', 4, 14);
insert into comments (comment, date, post_id, user_id) values ('consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in', '1554723799', 15, 13);
insert into comments (comment, date, post_id, user_id) values ('in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus', '1552961576', 17, 10);
insert into comments (comment, date, post_id, user_id) values ('quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae', '1553790565', 20, 5);
insert into comments (comment, date, post_id, user_id) values ('ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient', '1563644330', 14, 18);
insert into comments (comment, date, post_id, user_id) values ('justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit', '1552302620', 10, 4);
insert into comments (comment, date, post_id, user_id) values ('elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante', '1558373633', 7, 14);
insert into comments (comment, date, post_id, user_id) values ('lorem quisque ut erat curabitur gravida nisi at nibh in hac', '1536313998', 9, 18);
insert into comments (comment, date, post_id, user_id) values ('vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum', '1548484970', 19, 2);
insert into comments (comment, date, post_id, user_id) values ('turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis', '1554359602', 1, 17);
insert into comments (comment, date, post_id, user_id) values ('nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', '1540928315', 13, 4);
insert into comments (comment, date, post_id, user_id) values ('ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris', '1554878466', 6, 14);
insert into comments (comment, date, post_id, user_id) values ('nullam orci pede venenatis non sodales sed tincidunt eu felis', '1532815293', 3, 3);
insert into comments (comment, date, post_id, user_id) values ('vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit', '1545568820', 11, 14);
insert into comments (comment, date, post_id, user_id) values ('vestibulum velit id pretium iaculis diam erat fermentum justo nec', '1535267702', 7, 6);
insert into comments (comment, date, post_id, user_id) values ('est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam', '1535247160', 2, 19);
insert into comments (comment, date, post_id, user_id) values ('mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at', '1555833964', 11, 11);
insert into comments (comment, date, post_id, user_id) values ('lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis', '1533616646', 2, 7);
insert into comments (comment, date, post_id, user_id) values ('congue elementum in hac habitasse platea dictumst morbi vestibulum velit', '1555477946', 8, 9);
insert into comments (comment, date, post_id, user_id) values ('mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent', '1543531759', 3, 8);
insert into comments (comment, date, post_id, user_id) values ('etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus', '1557678769', 2, 16);
insert into comments (comment, date, post_id, user_id) values ('mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac', '1544572389', 2, 6);
insert into comments (comment, date, post_id, user_id) values ('non ligula pellentesque ultrices phasellus id sapien in sapien iaculis', '1537817061', 11, 19);
insert into comments (comment, date, post_id, user_id) values ('lacus at velit vivamus vel nulla eget eros elementum pellentesque', '1536573974', 18, 3);
insert into comments (comment, date, post_id, user_id) values ('lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis', '1554085816', 6, 5);
insert into comments (comment, date, post_id, user_id) values ('nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus', '1557011038', 9, 13);
insert into comments (comment, date, post_id, user_id) values ('varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas', '1536827243', 7, 14);
insert into comments (comment, date, post_id, user_id) values ('convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia', '1562119155', 12, 4);
insert into comments (comment, date, post_id, user_id) values ('justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus', '1537534463', 5, 20);
insert into comments (comment, date, post_id, user_id) values ('morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id', '1539725628', 16, 10);
insert into comments (comment, date, post_id, user_id) values ('tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla', '1541531936', 8, 19);
insert into comments (comment, date, post_id, user_id) values ('habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', '1548329772', 18, 13);
insert into comments (comment, date, post_id, user_id) values ('nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis', '1536358411', 11, 9);
insert into comments (comment, date, post_id, user_id) values ('faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis', '1564065050', 14, 11);
insert into comments (comment, date, post_id, user_id) values ('pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel', '1558268325', 14, 16);
insert into comments (comment, date, post_id, user_id) values ('nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', '1552812731', 10, 13);
insert into comments (comment, date, post_id, user_id) values ('nulla sed accumsan felis ut at dolor quis odio consequat varius', '1539524493', 2, 12);
insert into comments (comment, date, post_id, user_id) values ('luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum', '1543408263', 2, 17);
insert into comments (comment, date, post_id, user_id) values ('ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor', '1546919535', 5, 12);
insert into comments (comment, date, post_id, user_id) values ('nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida', '1544394953', 16, 7);
insert into comments (comment, date, post_id, user_id) values ('maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac', '1536221538', 6, 10);
insert into comments (comment, date, post_id, user_id) values ('posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis', '1541414581', 8, 12);
insert into comments (comment, date, post_id, user_id) values ('aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis', '1560558607', 8, 18);
insert into comments (comment, date, post_id, user_id) values ('ipsum primis in faucibus orci luctus et ultrices posuere cubilia', '1541933681', 8, 19);
insert into comments (comment, date, post_id, user_id) values ('dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus', '1557589950', 15, 2);
insert into comments (comment, date, post_id, user_id) values ('integer ac neque duis bibendum morbi non quam nec dui luctus', '1554638500', 4, 14);
insert into comments (comment, date, post_id, user_id) values ('ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', '1544580031', 9, 7);
insert into comments (comment, date, post_id, user_id) values ('platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum', '1532994854', 14, 14);
insert into comments (comment, date, post_id, user_id) values ('adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis', '1540960035', 12, 1);
insert into comments (comment, date, post_id, user_id) values ('leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa', '1535878946', 1, 5);
insert into comments (comment, date, post_id, user_id) values ('ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque', '1538240951', 17, 20);
insert into comments (comment, date, post_id, user_id) values ('non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', '1561273152', 16, 4);
insert into comments (comment, date, post_id, user_id) values ('curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', '1562613343', 15, 9);
insert into comments (comment, date, post_id, user_id) values ('cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus', '1546074257', 9, 5);
insert into comments (comment, date, post_id, user_id) values ('nullam orci pede venenatis non sodales sed tincidunt eu felis', '1539824948', 20, 1);
insert into comments (comment, date, post_id, user_id) values ('nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper', '1543991735', 20, 1);
insert into comments (comment, date, post_id, user_id) values ('quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam', '1551076965', 13, 15);
insert into comments (comment, date, post_id, user_id) values ('ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus', '1547010364', 19, 1);
insert into comments (comment, date, post_id, user_id) values ('fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', '1555747759', 3, 18);
insert into comments (comment, date, post_id, user_id) values ('diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam', '1560958923', 18, 20);
insert into comments (comment, date, post_id, user_id) values ('curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi', '1563826738', 14, 14);
insert into comments (comment, date, post_id, user_id) values ('et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis', '1535824004', 12, 7);
insert into comments (comment, date, post_id, user_id) values ('duis at velit eu est congue elementum in hac habitasse', '1557381300', 5, 5);
insert into comments (comment, date, post_id, user_id) values ('lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec', '1542491055', 4, 8);
insert into comments (comment, date, post_id, user_id) values ('consequat dui nec nisi volutpat eleifend donec ut dolor morbi', '1538458261', 15, 19);
insert into comments (comment, date, post_id, user_id) values ('in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh', '1562627411', 10, 16);
insert into comments (comment, date, post_id, user_id) values ('consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices', '1535375412', 10, 3);
insert into comments (comment, date, post_id, user_id) values ('odio porttitor id consequat in consequat ut nulla sed accumsan felis', '1548647556', 16, 15);
insert into comments (comment, date, post_id, user_id) values ('eu orci mauris lacinia sapien quis libero nullam sit amet turpis', '1541633694', 10, 10);
insert into comments (comment, date, post_id, user_id) values ('ultricies eu nibh quisque id justo sit amet sapien dignissim', '1559198743', 19, 11);
insert into comments (comment, date, post_id, user_id) values ('posuere felis sed lacus morbi sem mauris laoreet ut rhoncus', '1547217540', 14, 4);
insert into comments (comment, date, post_id, user_id) values ('nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat', '1561399368', 7, 2);
insert into comments (comment, date, post_id, user_id) values ('non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis', '1544877108', 6, 1);
insert into comments (comment, date, post_id, user_id) values ('turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', '1540316759', 20, 6);
insert into comments (comment, date, post_id, user_id) values ('mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero', '1553242764', 7, 4);
insert into comments (comment, date, post_id, user_id) values ('habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', '1555729712', 19, 20);
insert into comments (comment, date, post_id, user_id) values ('placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit', '1540947558', 9, 5);
insert into comments (comment, date, post_id, user_id) values ('erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis', '1543284347', 9, 15);
insert into comments (comment, date, post_id, user_id) values ('gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', '1555440584', 17, 3);
insert into comments (comment, date, post_id, user_id) values ('rutrum ac lobortis vel dapibus at diam nam tristique tortor eu', '1556060073', 10, 14);
insert into comments (comment, date, post_id, user_id) values ('dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel', '1550223764', 18, 15);
insert into comments (comment, date, post_id, user_id) values ('aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas', '1545309731', 19, 20);
insert into comments (comment, date, post_id, user_id) values ('arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec', '1561904339', 17, 9);
insert into comments (comment, date, post_id, user_id) values ('iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus', '1559149655', 3, 19);
insert into comments (comment, date, post_id, user_id) values ('proin at turpis a pede posuere nonummy integer non velit', '1546934775', 3, 20);
insert into comments (comment, date, post_id, user_id) values ('pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper', '1551284311', 5, 12);
insert into comments (comment, date, post_id, user_id) values ('sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', '1541951367', 4, 17);
insert into comments (comment, date, post_id, user_id) values ('in eleifend quam a odio in hac habitasse platea dictumst maecenas', '1554142108', 6, 17);
insert into comments (comment, date, post_id, user_id) values ('mi in porttitor pede justo eu massa donec dapibus duis at velit', '1559405656', 18, 3);
insert into comments (comment, date, post_id, user_id) values ('duis mattis egestas metus aenean fermentum donec ut mauris eget massa', '1561422224', 11, 5);
insert into comments (comment, date, post_id, user_id) values ('sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien', '1543420994', 13, 3);
insert into comments (comment, date, post_id, user_id) values ('consequat ut nulla sed accumsan felis ut at dolor quis odio consequat', '1551286844', 2, 12);
insert into comments (comment, date, post_id, user_id) values ('faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec', '1536316160', 8, 3);
insert into comments (comment, date, post_id, user_id) values ('in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam', '1559338677', 4, 20);
insert into comments (comment, date, post_id, user_id) values ('vestibulum proin eu mi nulla ac enim in tempor turpis nec', '1553623520', 19, 15);